
version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: security_scan_db
    # volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U security_scan_db"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  app:
    build: .
    depends_on:
      # db:
        # condition: service_healthy
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=test
      - DB_PASSWORD=testpassword
      - DB_NAME=security_scan_db

