
version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - ./user-db-backup:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U security_scan_db"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  app:
    build: .
    volumes: 
      - ./:/app
    depends_on:
      # db:
        # condition: service_healthy
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app_db

