name: Security Scan CI/CD

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
        
jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.7'

      - name: Run Security Scan
        # run: go run main.go vulnerable-app
        # For now, wont be testing any vulnerable code
        run: go run main.go

      - name: Fail Build on Vulnerabilities
        if: failure()
        run: echo "Vulnerabilities detected! Please fix before merging."
